project_id = "duaslinguas_-_supabase"

[api]
enabled = true
port = 55431

[auth.hook.custom_access_token] 
enabled = true
uri = "pg-functions://postgres/public/custom_access_token_hook"

[db]
port = 55432
shadow_port = 55430
major_version = 17

[db.pooler]
enabled = false
port = 55439

[studio]
enabled = true
port = 55433
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 55434
# smtp_port = 55435
# pop3_port = 55436

[analytics]
enabled = true
port = 55437

[edge_runtime]
enabled = true
inspector_port = 8183

[functions.init_book_chapters]
enabled = true
verify_jwt = true
import_map = "./functions/init_book_chapters/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/init_book_chapters/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/init_book_chapters/*.html" ]


[functions.bulk_chapters]
enabled = true
verify_jwt = true
import_map = "./functions/bulk_chapters/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bulk_chapters/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bulk_chapters/*.html" ]

[functions.embed]
enabled = true
verify_jwt = true
import_map = "./functions/embed/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/embed/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/embed/*.html" ]
