export default {
  error: {
    saving: "Error saving the register.",
    updating: "Error updating the register.",
    fetching: "Error fetching the register.",
  },
  success: {
    saving: "Register saved successfully!",
    updating: "Register updated successfully!",
  },
  loading: {
    saving: "Saving...",
    updating: "Updating...",
  },
  books: {
    title: "Books",
    newTitle: "New Book",
    editTitle: "Edit Book",
    description: "Add a new book to be processed.",
    submitButton: "Add Book",
    updateButton: "Update Book",
    chapters: "Chapters",
  },
  categories: {
    title: "Categories",
    newTitle: "New Category",
    editTitle: "Edit Category",
    description: "Add a new category to classify books.",
    submitButton: "Add Category",
    updateButton: "Update Category",
  },
  book_categories: {
    title: "Book Categories",
    newTitle: "New Book Category",
    editTitle: "Edit Book Category",
    description: "Link a book to a category.",
    submitButton: "Link Book to Category",
    updateButton: "Update Book Category",
  },
  read: {
    changedChapterTo: "Changed to chapter number: {{chapterNumber}}",
    loadingChapter: "Loading chapter number: {{chapterNumber}}",
    reading: "Reading the book: {{bookTitle}}",
    warning_first:
      "The snippets here provided are solely to be used as a way to resume this book and quiz your knowledge. They are generated by AI and thus are subject to errors.",
    warning_second:
      "If you are liking this book, we recommend following <0>this link</0> to buy the book. We will receive a small percentage if you do so.",
  },
  preferences: {
    title: "Preferences",
    description: "Manage your application preferences.",
  },
  dashboard: {
    title: "Dashboard",
    description: "Welcome to the Dashboard!",
  },
};
