name: Supabase Deploy Functions

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Supabase Functions with custom JWT rules
        run: |
          cd supabase/functions

          NO_VERIFY_JWT_FUNCTIONS=("bulk_chapters" "embed" "init_book_chapters")

          for dir in */ ; do
            FUNCTION_NAME=${dir%/}

            if [[ -f "${FUNCTION_NAME}/index.ts" || -f "${FUNCTION_NAME}/index.js" ]];  then
              if [[ " ${NO_VERIFY_JWT_FUNCTIONS[@]} " =~ " ${FUNCTION_NAME} " ]]; then
                echo "Deploying ${FUNCTION_NAME} with --no-verify-jwt"
                supabase functions deploy $FUNCTION_NAME --project-ref $PROJECT_ID      --no-verify-jwt
              else
                echo "Deploying ${FUNCTION_NAME} with default JWT verification"
                supabase functions deploy $FUNCTION_NAME --project-ref $PROJECT_ID
              fi
            else
              echo "Skipping ${FUNCTION_NAME} (no index.ts or index.js found)"
            fi
          done